name: Download data
on:
  schedule:
    - cron: '0 0 * * *'
# on:
#   push:
#     branches:
#       - main
  
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: wget
        run: |
          wget http://exoplanet.eu/catalog/csv -O exoplanetEU.csv

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Updated data'
          add: 'exoplanetEU.csv'